<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Welcome Back</name>
   <tag></tag>
   <elementGuidId>0cb1ad0f-e97c-4914-b5ab-f78ba6d5747c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.p-toast-detail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' p-toast-detail ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Welcome Back&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5c0bfe7-a8e4-4a65-8247-d4afd9d954c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-toast-detail</value>
      <webElementGuid>ebe5a19f-8f0c-4a79-b7cc-341cd85eadd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>fc69cda7-fd2e-408a-86c9-fb15d225371e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>detail</value>
      <webElementGuid>d613a59f-b722-484a-9886-7daac68ecc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome Back</value>
      <webElementGuid>066a5708-5fdd-4368-b6ee-b28cdc7d61cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6ad07a2ac8d8cab7c533026de72c01c3</value>
      <webElementGuid>6094d8f7-8a2f-4b80-a581-cca11e53066e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' p-toast-detail ')]</value>
      <webElementGuid>ba13da37-a527-4fe3-89e6-280065071d68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' p-toast-detail ')]</value>
      <webElementGuid>80965498-0f4b-4df5-ad22-ad6f353bb821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Welcome Back' or . = 'Welcome Back')]</value>
      <webElementGuid>6a1c9e69-8d27-4753-97ec-39ce71edc996</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
