<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your Email</name>
   <tag></tag>
   <elementGuidId>27812388-766e-488e-949e-7c70c2259023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[pc5=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@pc5 = '']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Your Email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ed14f52-3d84-4baa-9848-71e48c7fd7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a77d43ec-4135-4de0-819d-cde0da591c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-inputtext-lg p-inputfield-lg p-inputtext-fluid</value>
      <webElementGuid>6e5d9f20-8047-434b-a4f5-06906ca47fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e468bc47-4205-4c8d-83af-411cad137beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p</name>
      <type>Main</type>
      <value>fluid large</value>
      <webElementGuid>1fcbf17e-1ab9-4e0e-a5c0-460604990d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Email</value>
      <webElementGuid>11d0718b-3ca8-40f6-8e34-20f95704531a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>63852b82-feda-42cf-9467-bad7ca49b99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>637fb9ac-b45f-46cf-ae49-f4da77db313c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ffc685bdeb1957281983e452eb0c1ed4</value>
      <webElementGuid>67fe476f-ca2f-4c62-bd99-624b0987f8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@pc5 = '']</value>
      <webElementGuid>42d9f660-a3f8-4ea5-a55c-60d99f903a92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@pc5 = '']</value>
      <webElementGuid>ac003555-e96b-4307-ad5f-79854592c23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email' and @placeholder = 'Your Email']</value>
      <webElementGuid>6b1818af-b4c9-46d6-ae89-198b2a2ca11c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
